---

version: "3"

services:

  gempdb:
    container_name: gempdb
    hostname: gempdb
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      - "MYSQL_ROOT_PASSWORD=gempukku"
      - "MYSQL_DATABASE=gemp-swccg"
      - "MYSQL_USER=gemp"
      - "MYSQL_PASSWORD=Four_mason8pirate"
    image: gempdb
    expose:
      - "3306/tcp"
    ports:
      # Change this to any convenient ports on your host system.
      # Change the published port to any convenient port on your host system.
      - target: 3306
        published: 3306
    restart: unless-stopped
    labels:
      - "app=gempdb"
      - "traefik.enable=false"      

  gemp:
    container_name: gemp
    hostname: gemp
    build:
      context: .
      dockerfile: Dockerfile
    image: gemp
    expose:
      - "8080/tcp"
    restart: unless-stopped
    ports:
      # Change these to any convenient ports on your host system.
      # Change the published ports to any convenient ports on your host system.
      # Gemp ports
      - target: 8080
        published: 8080
      # Debugger ports
      - target: 8000
        published: 8000
    volumes:
      - type: bind
        source: ./gemp-swccg-async/src/main/web/
        target: /opt/gemp-swccg/web
      - type: bind
        source: ./gemp-swccg-async/target/web.jar
        target: /opt/gemp-swccg/web.jar
      - type: bind
        source: ./logs
        target: /logs
      - type: bind
        source: ./replay
        target: /replay
    labels:
      - "app=gemp"
      - "traefik.enable=true"
    tty: true
    depends_on:
      - gempdb
    environment:
      - "db_hostname=gempdb"
      - "environment=test"
    command: ["/usr/bin/wait-for-it.sh", "gempdb:3306", "--",
              "/usr/bin/java",
              "-Xmx4g",
              "-Dlog4j.debug",
              "-Dlog4j.configuration=test-log4j.xml",
              "-cp", "web.jar",
              "com.gempukku.swccgo.async.SwccgoAsyncServer"]
