---

version: "3"

services:
  gemp:
    volumes:
      - type: bind
        source: ./gemp-swccg-async/src/main/web/
        target: /opt/gemp-swccg/web
      - type: bind
        source: ./gemp-swccg-async/target/web.jar
        target: /opt/gemp-swccg/web.jar
    environment:
      - "environment=test"