---

version: "3"


services:

  gempdb:
    container_name: gempdb
    hostname: gempdb
    build:
      context: .
      dockerfile: db.Dockerfile
    environment:
      - "MYSQL_ROOT_PASSWORD=gempukku"
      - "MYSQL_DATABASE=gemp-swccg"
      - "MYSQL_USER=gemp"
      - "MYSQL_PASSWORD=Four_mason8pirate"
    image: gempdb
    expose:
      - "3306/tcp"
    ports:
      - "3306:3306"
    restart: unless-stopped
    labels:
      - "app=gempdb"
      - "traefik.enable=false"

  gemp:
    container_name: gemp
    hostname: gemp
    build:
      context: .
      dockerfile: Dockerfile
    image: gemp
    expose:
      - "8080/tcp"
    restart: unless-stopped
    ports:
      - "8080:8080"
    labels:
      - "app=gemp"
      - "traefik.enable=true"
    tty: true
    depends_on:
      - gempdb
    volumes:
       - type: bind
         source: ./gemp-swccg-async/src/main/web/
         target: /opt/gemp-swccg/web
    environment:
      - "db_hostname=gempdb"
    command: ["/usr/bin/wait-for-it.sh", "gempdb:3306", "--",
              "/usr/bin/java",
              "-Xmx4g",
              "-Dlog4j.debug",
              "-Dlog4j.configuration=prod-log4j.xml",
              "-cp", "web.jar",
              "com.gempukku.swccgo.async.SwccgoAsyncServer"]