package com.gempukku.swccgo.common;

/**
 * Represents each persona in the SWCCG card game.
 */
public enum Persona implements Filterable {
    // Characters
    _4_LOM("4-LOM"),
    ACKBAR("Ackbar"),
    AHSOKA("Ahsoka"),
    AMIDALA("Amidala"),
    ANAKIN("Anakin"),
    APHRA("Aphra"),
    ARMORER("Armorer"),
    AURRA("Aurra"),
    BAZE("Baze"),
    BB8("BB-8"),
    BEAUMONT("Beaumont"),
    BECKETT("Beckett"),
    BEEDO("Beedo"),
    BEN_SOLO("Ben Solo"),
    BIB("Bib Fortuna"),
    BLIZZARD_1("Blizzard 1"),
    BOBA_FETT("Boba Fett"),
    BO_KATAN("Bo-Katan"),
    BOOSTER("Booster"),
    BOSSK("Bossk"),
    C3PO("C-3PO"),
    CAD("Cad"),
    CAL("Cal"),
    CAL_KESTIS("Cal Kestis"),
    CARA_DUNE("Cara Dune"),
    CASSIAN("Cassian"),
    CHEWIE("Chewie"),
    CHOPPER("Chopper"),
    CONNIX("Connix"),
    CORRAN_HORN("Corran Horn"),
    CRACKEN("Cracken"),
    DACK("Dack Ralter"),
    DANNIK("Dannik Jerriko"),
    DASH("Dash"),
    DENGAR("Dengar"),
    DIN("Din"),
    DJ("DJ"),
    DOALLYN("Doallyn"),
    DOFINE("Dofine"),
    DOIKK_NATS("Doikk Na'ts"),
    DOOKU("Dooku"),
    DS_61_2("DS-61-2"),
    DS_61_3("DS-61-3"),
    DUTCH("Dutch"),
    ELIS("Elis"),
    EZRA("Ezra"),
    GALEN("Galen"),
    FENNEC_SHAND("Fennec Shand"),
    FIGRIN_DAN("Figrin D'an"),
    GIDEON("Gideon"),
    GREEF("Greef"),
    GREEN_LEADER("Green Leader"),
    GRIEVOUS("Grievous"),
    GROGU("Grogu"),
    GRONDORN("Grondorn"),
    GUNRAY("Gunray"),
    HAAKO("Haako"),
    HAN("Han"),
    HET("Het"),
    ICKABEL_GONT("Ickabel G'ont"),
    IG11("IG-11"),
    IG88("IG-88"),
    JABBA("Jabba"),
    JAINA("Jaina"),
    JANGO_FETT("Jango"),
    JANNAH("Jannah"),
    JANSE("Janse"),
    JAR_JAR("Jar Jar"),
    JENDON("Jendon"),
    JERUS("Jerus"),
    JONUS("Jonus"),
    JUNKIN("Junkin"),
    JUNO("Juno Eclipse"),
    JYN("Jyn Erso"),
    KANAN("Kanan"),
    KETWOL("Ketwol"),
    KHURGEE("Khurgee"),
    KRENNIC("Krennic"),
    KURUK("Kuruk"),
    KYLO("Kylo"),
    L3_37("L3-37"),
    LADY_VADER("Lady Vader"),
    LANDO("Lando"),
    LAUDICA("Laudica"),
    LEIA("Leia"),
    LOBOT("Lobot"),
    LOTT("Lott"),
    LUKE("Luke"),
    MAAREK_STELE("Maarek Stele"),
    MARA_JADE("Mara Jade"),
    MARA_SKYWALKER("Mara Skywalker"),
    MARGO("Margo"),
    MARQUAND("Marquand"),
    MACE("Mace"),
    MAUL("Maul"),
    MAZ("Maz"),
    MCQUARRIE("McQuarrie"),
    MELSHI("Melshi"),
    MON_MOTHMA("Mon Mothma"),
    MOTTI("Motti"),
    NALAN_CHEEL("Nalan Cheel"),
    NARTHAX("Narthax"),
    NIEN_NUNB("Nien Nunb"),
    OBIWAN("Obi-Wan"),
    OCHI("Ochi"),
    ODD_BALL("Odd ball"),
    OS_72_1("OS-72-1"),
    OS_72_2("OS-72-2"),
    OZZEL("Ozzel"),
    PANAKA("Panaka"),
    PAPLOO("Paploo"),
    PEROSEI("Perosei"),
    PIETT("Piett"),
    PLO("Plo Koon"),
    POE("Poe Dameron"),
    PRE_VIZSLA("Pre Vizsla"),
    PROFUNDITY("Profundity"),
    PROXIMA("Proxima"),
    PRYCE("Pryce"),
    PRYDE("Pryde"),
    PUCK("Puck"),
    QUEENS_ROYAL_STARSHIP("Queen's Royal Starship"),
    QUIGON("Qui-Gon"),
    QIRA("Qi'ra"),
    R2D2("R2-D2"),
    RAYC("Rayc"),
    RIC("Ric"),
    RED_LEADER("Red Leader"),
    REY("Rey"),
    ROSE("Rose"),
    SABE("Sabe"),
    SACHE("Sache"),
    SEFLA("Sefla"),
    SEVENTH_SISTER("Seventh Sister"),
    SHAWN("Shawn"),
    SIDIOUS("Sidious"),
    SNAP("Snap Wexley"),
    SNOKE("Snoke"),
    SON_OF_VADER("Son Of Vader"),
    TALLIE_LINTRA("Tallie"),
    TARKIN("Tarkin"),
    TEDN_DAHAI("Tedn Dahai"),
    THEDIT("Thedit"),
    THRAWN("Thrawn"),
    TIGRAN("Tigran"),
    TYCHO("Tycho"),
    VADER("Vader"),
    VAL("Val"),
    VANEE("Vanee"),
    VANTO("Vanto"),
    VEERS("Veers"),
    VENTRESS("Ventress"),
    VOS("Vos"),
    VUL("Vul"),
    WEDGE("Wedge"),
    WES("Wes Janson"),
    WUHER("Wuher"),
    YODA("Yoda"),
    YULAREN("Yularen"),
    ZUCKUSS("Zuckuss"),

    // Starships
    BESTOON_LEGACY("Bestoon Legacy"),
    BLACK_1("Black 1"),
    BLACK_2("Black 2"),
    BLACK_3("Black 3"),
    BLOCKADE_FLAGSHIP("Blockade Flagship"),
    BLUE_11("Blue 11"),
    BLUE_SQUADRON_1("Blue Squadron 1"),
    CHIMAERA("Chimaera"),
    EXECUTOR("Executor"),
    FALCON("Falcon"),
    FIRST_LIGHT("First Light"),
    GOLD_1("Gold 1"),
    GREEN_SQUADRON_1("Green Squadron 1"),
    GREEN_SQUADRON_3("Green Squadron 3"),
    HOME_ONE("Home One"),
    HOUNDS_TOOTH("Hound's Tooth"),
    IG2000("IG-2000"),
    INVISIBLE_HAND("Invisible Hand"),
    LIBERTINE("Libertine"),
    MAULS_SITH_INFILTRATOR("Maul's Sith Infiltrator"),
    MIST_HUNTER("Mist Hunter"),
    ONYX_1("Onyx 1"),
    PULSAR_SKATE("Pulsar Skate"),
    PUNISHING_ONE("Punishing One"),
    RADIANT_VII("Radiant VII"),
    RAZOR_CREST("Razor Crest"),
    RED_1("Red 1"),
    RED_2("Red 2"),
    RED_5("Red 5"),
    RIO("Rio"),
    RUKH("Rukh"),
    SCIMITAR_2("Scimitar 2"),
    SLAVE_I("Slave I"),
    SUPREMACY("Supremacy"),
    STEADFAST("Steadfast"),
    TANTIVE_IV("Tantive IV"),
    VADERS_CUSTOM_TIE("Vader's Custom TIE"),
    VADERS_PERSONAL_SHUTTLE("Vader's Personal Shuttle"),

    // Vehicles
    JABBAS_SAIL_BARGE("Jabba's Sail Barge"),

    // Weapons
    AHSOKAS_LIGHTSABERS("Ahsoka's Lightsabers"),
    AHSOKAS_SHOTO_LIGHTSABER("Ahsoka's Shoto Lightsaber"),
    ANAKINS_LIGHTSABER("Anakin's Lightsaber"),
    ASAJJS_LIGHTSABERS("Asajj's Lightsabers"),
    AURRAS_BLASTER_RIFLE("Aurra Sing's Blaster Rifle"),
    EZRAS_BLASTER_LIGHTSABER("Ezra's Blaster Lightsaber"),
    GALENS_LIGHTSABER("Galen's Lightsaber"),
    KYLOS_LIGHTSABER("Kylo's Lightsaber"),
    LADY_VADERS_BLASTER_RIFLE("Lady Vader's Blaster Rifle"),
    LEIAS_BLASTER_RIFLE("Leia's Blaster Rifle"),
    LEIAS_LIGHTSABER("Leia's Lightsaber"),
    LUKES_LIGHTSABER("Luke's Lightsaber"),
    MARA_JADES_LIGHTSABER("Mara Jade's Lightsaber"),
    MARA_SKYWALKERS_LIGHTSABER("Mara Skywalker's Lightsaber"),
    MAULS_DOUBLE_BLADED_LIGHTSABER("Maul's Double-Bladed Lightsaber"),
    QUIGON_JINNS_LIGHTSABER("Qui-Gon Jinn's Lightsaber"),
    SIDIOUS_LIGHTSABER("Sidious' Lightsaber"),
    SON_OF_VADERS_LIGHTSABER("Son Of Vader's Lightsaber"),
    VADERS_LIGHTSABER("Vader's Lightsaber"),
    ZUCKUSS_SNARE_RIFLE("Zuckuss' Snare Rifle"),

    ;



    private String _humanReadable;

    Persona(String humanReadable) {
        _humanReadable = humanReadable;
    }

    public String getHumanReadable() {
        return _humanReadable;
    }

    public Persona getCrossedOverPersona() {
        if (equals(ANAKIN)) return VADER;
        if (equals(LADY_VADER)) return LEIA;
        if (equals(LEIA)) return LADY_VADER;
        if (equals(LUKE)) return SON_OF_VADER;
        if (equals(MARA_JADE)) return MARA_SKYWALKER;
        if (equals(MARA_SKYWALKER)) return MARA_JADE;
        if (equals(SON_OF_VADER)) return LUKE;
        if (equals(VADER)) return ANAKIN;
        if (equals(BEN_SOLO)) return KYLO;
        if (equals(KYLO)) return BEN_SOLO;
        if (equals(ANAKINS_LIGHTSABER)) return VADERS_LIGHTSABER;
        if (equals(LADY_VADERS_BLASTER_RIFLE)) return LEIAS_BLASTER_RIFLE;
        if (equals(LEIAS_BLASTER_RIFLE)) return LADY_VADERS_BLASTER_RIFLE;
        if (equals(LUKES_LIGHTSABER)) return SON_OF_VADERS_LIGHTSABER;
        if (equals(MARA_JADES_LIGHTSABER)) return MARA_SKYWALKERS_LIGHTSABER;
        if (equals(MARA_SKYWALKERS_LIGHTSABER)) return MARA_JADES_LIGHTSABER;
        if (equals(SON_OF_VADERS_LIGHTSABER)) return LUKES_LIGHTSABER;
        if (equals(VADERS_LIGHTSABER)) return ANAKINS_LIGHTSABER;
        return this;
    }
}
