const packBlueprints = {
    "Premiere Booster Pack":"https://res.starwarsccg.org/packs/premiere_booster_pack.png",
    "A New Hope Booster Pack":"https://res.starwarsccg.org/packs/a_new_hope_booster_pack.png",
    "Hoth Booster Pack":"https://res.starwarsccg.org/packs/hoth_booster_pack.png",
    "Dagobah Booster Pack":"https://res.starwarsccg.org/packs/dagobah_booster_pack.png",
    "Cloud City Booster Pack":"https://res.starwarsccg.org/packs/cloud_city_booster_pack.png",
    "Jabba's Palace Booster Pack":"https://res.starwarsccg.org/packs/jabbas_palace_booster_pack.png",
    "Special Edition Booster Pack":"https://res.starwarsccg.org/packs/special_edition_booster_pack.png",
    "Endor Booster Pack":"https://res.starwarsccg.org/packs/endor_booster_pack.png",
    "Endor Booster Pack (no random foils)":"https://res.starwarsccg.org/packs/endor_booster_pack.png",
    "Death Star II Booster Pack":"https://res.starwarsccg.org/packs/death_star_2_booster_pack.png",
    "Tatooine Booster Pack":"https://res.starwarsccg.org/packs/tatooine_booster_pack.png",
    "Tatooine Booster Pack (Episode I only)":"https://res.starwarsccg.org/packs/tatooine_booster_pack.png",
    "Coruscant Booster Pack":"https://res.starwarsccg.org/packs/coruscant_booster_pack.png",
    "Coruscant Booster Pack (Episode I only)":"https://res.starwarsccg.org/packs/coruscant_booster_pack.png",
    "Theed Palace Booster Pack":"https://res.starwarsccg.org/packs/theed_palace_booster_pack.png",
    "Reflections Booster Pack":"https://res.starwarsccg.org/packs/reflections_booster_pack.png",
    "Reflections II Booster Pack":"https://res.starwarsccg.org/packs/reflections_2_booster_pack.png",
    "Reflections III Booster Pack":"https://res.starwarsccg.org/packs/reflections_3_booster_pack.png",
    "Reflections III Booster Pack (Episode I only no shields)":"https://res.starwarsccg.org/packs/reflections_3_booster_pack.png",

    "Premiere Booster Box":"https://res.starwarsccg.org/packs/premiere_booster_box.png",
    "A New Hope Booster Box":"https://res.starwarsccg.org/packs/a_new_hope_booster_box.png",
    "Hoth Booster Box":"https://res.starwarsccg.org/packs/hoth_booster_box.png",
    "Dagobah Booster Box":"https://res.starwarsccg.org/packs/dagobah_booster_box.png",
    "Cloud City Booster Box":"https://res.starwarsccg.org/packs/cloud_city_booster_box.png",
    "Jabba's Palace Booster Box":"https://res.starwarsccg.org/packs/jabbas_palace_booster_box.png",
    "Special Edition Booster Box":"https://res.starwarsccg.org/packs/special_edition_booster_box.png",
    "Endor Booster Box":"https://res.starwarsccg.org/packs/endor_booster_box.png",
    "Death Star II Booster Box":"https://res.starwarsccg.org/packs/death_star_2_booster_box.png",
    "Tatooine Booster Box":"https://res.starwarsccg.org/packs/tatooine_booster_box.png",
    "Coruscant Booster Box":"https://res.starwarsccg.org/packs/coruscant_booster_box.png",
    "Theed Palace Booster Box":"https://res.starwarsccg.org/packs/theed_palace_booster_box.png",
    "Reflections Booster Box":"https://res.starwarsccg.org/packs/reflections_booster_box.png",
    "Reflections II Booster Box":"https://res.starwarsccg.org/packs/reflections_2_booster_box.png",
    "Reflections III Booster Box":"https://res.starwarsccg.org/packs/reflections_3_booster_box.png",

    "Premiere Starter Set":"https://res.starwarsccg.org/packs/premiere_starter_set.png",
    "Special Edition Starter Deck - Dark":"https://res.starwarsccg.org/packs/special_edition_starter_deck_dark.png",
    "Special Edition Starter Deck - Light":"https://res.starwarsccg.org/packs/special_edition_starter_deck_light.png",
    "Death Star II Pre-Constructed Deck - Dark":"https://res.starwarsccg.org/packs/death_star_2_pre_constructed_deck_dark.png",
    "Death Star II Pre-Constructed Deck - Light":"https://res.starwarsccg.org/packs/death_star_2_pre_constructed_deck_light.png",

    "EPP - Darth Vader With Lightsaber":"https://res.starwarsccg.org/packs/enhanced_premiere_pack_darth_vader.png",
    "EPP - Luke With Lightsaber":"https://res.starwarsccg.org/packs/enhanced_premiere_pack_luke.png",
    "EPP - Boba Fett With Blaster Rifle":"https://res.starwarsccg.org/packs/enhanced_premiere_pack_boba_fett.png",
    "EPP - Obi-Wan With Lightsaber":"https://res.starwarsccg.org/packs/enhanced_premiere_pack_obiwan.png",
    "EPP - Han With Heavy Blaster Pistol":"https://res.starwarsccg.org/packs/enhanced_premiere_pack_han.png",
    "EPP - Leia With Blaster Rifle":"https://res.starwarsccg.org/packs/enhanced_premiere_pack_leia.png",

    "ECCP - Boba Fett In Slave One":"https://res.starwarsccg.org/packs/enhanced_cloud_city_pack_boba_fett.png",
    "ECCP - Lando With Blaster Rifle":"https://res.starwarsccg.org/packs/enhanced_cloud_city_pack_lando.png",
    "ECCP - IG-88 With Riot Gun":"https://res.starwarsccg.org/packs/enhanced_cloud_city_pack_boba_ig88.png",
    "ECCP - Chewie With Blaster Rifle":"https://res.starwarsccg.org/packs/enhanced_cloud_city_pack_chewie.png",

    "EJPP - Boushh":"https://res.starwarsccg.org/packs/enhanced_jabbas_palace_pack_boushh.png",
    "EJPP - Mara Jade: The Emperor's Hand":"https://res.starwarsccg.org/packs/enhanced_jabbas_palace_pack_mara_jade.png",
    "EJPP - Master Luke":"https://res.starwarsccg.org/packs/enhanced_jabbas_palace_pack_boba_master_luke.png",
    "EJPP - See-Threepio":"https://res.starwarsccg.org/packs/enhanced_jabbas_palace_pack_seethreepio.png",

    "Jedi Pack":"https://res.starwarsccg.org/packs/jedi_pack.png",
    "Rebel Leader Pack":"https://res.starwarsccg.org/packs/rebel_leader_pack.png",
    "Virtual Alternate Image Booster Pack Series 1":"https://res.starwarsccg.org/packs/virtualalternateimageboosterpackseries1.png",
    "Virtual Alternate Image Booster Pack Series 2":"https://res.starwarsccg.org/packs/virtualalternateimageboosterpackseries2.png",
    "Virtual Alternate Image Booster Pack Series 3":"https://res.starwarsccg.org/packs/virtualalternateimageboosterpackseries3.png",
    "Virtual Alternate Image Booster Pack Series 4":"https://res.starwarsccg.org/packs/virtualalternateimageboosterpackseries4.png",
    "Virtual Alternate Image Booster Pack Series 5":"https://res.starwarsccg.org/packs/virtualalternateimageboosterpackseries5.png",
    "Virtual Alternate Image Booster Pack Series 6":"https://res.starwarsccg.org/packs/virtualalternateimageboosterpackseries6.png",
    "Virtual Alternate Image Booster Pack Series 7":"https://res.starwarsccg.org/packs/virtualalternateimageboosterpackseries7.png",
    "Virtual Alternate Image Booster Pack Series 8":"https://res.starwarsccg.org/packs/virtualalternateimageboosterpackseries8.png",

    "First Anthology Box":"https://res.starwarsccg.org/packs/first_anthology_box.png",
    "Second Anthology Box":"https://res.starwarsccg.org/packs/second_anthology_box.png",
    "Third Anthology Box":"https://res.starwarsccg.org/packs/third_anthology_box.png",

    "Official Tournament Sealed Deck":"https://res.starwarsccg.org/packs/official_tournament_sealed_deck.png",
    "Jabba's Palace Sealed Deck":"https://res.starwarsccg.org/packs/jabbas_palace_sealed_deck.png",

    "Premiere Intro Two-Player Game":"https://res.starwarsccg.org/packs/premiere_intro_two_player_game.png",
    "ESB Intro Two-Player Game":"https://res.starwarsccg.org/packs/esb_intro_two_player_game.png",

    "Watto's Cube Objective Pack (Dark)":"https://res.starwarsccg.org/packs/wattos_cube_objective_pack_dark.png",
    "Watto's Cube Objective Pack (Light)":"https://res.starwarsccg.org/packs/wattos_cube_objective_pack_light.png",
    "Watto's Cube Draft Pack (Dark)":"https://res.starwarsccg.org/packs/wattos_cube_draft_pack_dark.png",
    "Watto's Cube Draft Pack (Light)":"https://res.starwarsccg.org/packs/wattos_cube_draft_pack_light.png",
    "Watto's Cube Fixed Pack (Dark)":"https://res.starwarsccg.org/packs/wattos_cube_fixed_pack_dark.png",
    "Watto's Cube Fixed Pack (Light)":"https://res.starwarsccg.org/packs/wattos_cube_fixed_pack_light.png",


    "(S)Booster Choice -- Non-Reflections":"https://res.starwarsccg.org/packs/booster_selection.png",
    "(S)Booster Choice -- Reflections":"https://res.starwarsccg.org/packs/booster_selection.png",
    "(S)Enhanced Cloud City Pack Choice":"https://res.starwarsccg.org/packs/booster_selection.png",
    "(S)Enhanced Jabba's Palace Pack Choice":"https://res.starwarsccg.org/packs/booster_selection.png",
    "(S)Enhanced Premiere Pack Choice -- Dark":"https://res.starwarsccg.org/packs/booster_selection.png",
    "(S)Enhanced Premiere Pack Choice -- Light":"https://res.starwarsccg.org/packs/booster_selection.png",

};