package com.gempukku.swccgo.logic.modifiers;

// This enum represents the types of special
// modifier flags in Gemp-Swccg that affect
// the game as a whole and not just specific
// cards.
//
public enum ModifierFlag {
    LIGHT_SIDE_GOES_FIRST, LIFE_FORCE_HIDDEN_WHEN_LOST, MAY_NOT_ACTIVATE_FORCE,
    HALVE_AND_ROUND_UP_FORCE_LOSS, HALVE_AND_ROUND_DOWN_FORCE_LOSS,
    FORCE_DRAIN_LOST_FROM_RESERVE_DECK, FORCE_DRAIN_LOST_FROM_FORCE_PILE, ADD_DESTINY_AGAINST_COUNTER_SURPRISE_ASSAULT,
    HOTH_ENERGY_SHIELD_RULES_SUSPENDED, FORCE_RETRIEVAL_CANCELED,
    MAY_NOT_USE_WILD_CARDS_IN_SABACC, MAY_NOT_DEPLOY_INSERT_CARDS,
    DRAW_TWO_AND_CHOOSE_ONE_FOR_TRAINING_DESTINY,
    MAY_ONLY_USE_ONE_COMBAT_CARD_PER_TURN,
    BATTLE_DESTINY_MODIFIERS_AFFECT_TOTAL_BATTLE_DESTINY_INSTEAD,
    MAY_NOT_RETRIEVE_FORCE_FOR_INITIATING_BATTLE,
    TAKES_FIRST_BATTLE_WEAPONS_SEGMENT_ACTION,
    TAKES_FIRST_TWO_BATTLE_WEAPONS_SEGMENT_ACTIONS,
    WAMPAS_SELECTIVE_CREATURES_FOR_REMAINDER_OF_GAME,

    USED_PILES_FACE_UP,
    LOST_PILE_FACE_DOWN,

    DO_NOT_SKIP_LISTENER_UPDATES_DURING_FORCE_ACTIVATION
}
