---

name: Create GEMP Server Release

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags:
      - 'v*' # Push events to matching v*, i.e. v1.0, v20.15.10

jobs:
  build-gemp:
    runs-on: "ubuntu-latest"

    steps:
      - uses: actions/checkout@master

      - name: apt-get install OpenJDK
        run:  |
          which java ; true
          java -version ; true
          sudo apt-get install -y openjdk-11-jdk-headless
          java -version ; true

      - name: mvn build
        run: mvn clean install

      # https://github.com/actions/create-release
      - name: Create Release
        id: create_release
        uses: actions/create-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # This token is provided by Actions, you do not need to create your own token
        with:
          tag_name: ${{ github.ref }}
          release_name: Release ${{ github.ref }}
          body: ""
          draft: true
          prerelease: false

      # https://github.com/actions/upload-release-asset
      - name: Upload web.jar to Release
        id: upload_release_asset 
        uses: actions/upload-release-asset@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }} # This pulls from the CREATE RELEASE step above, referencing it's ID to get its outputs object, which include a `upload_url`. See this blog post for more info: https://jasonet.co/posts/new-features-of-github-actions/#passing-data-to-future-steps 
          asset_path: ./gemp-swccg-async/target/web.jar
          asset_name: web.jar
          asset_content_type: application/zip



