name: test-on-push
on:
  push:
    branches:
      - master
      - main

  pull_request:
    types:
    - opened
    - edited
    - synchronize

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7

      - name: Set up Java 21
        uses: actions/setup-java@v6
        with:
          distribution: temurin
          java-version: 21
          cache: maven

      - name: mvn build
        run: mvn clean install
        working-directory: src

      - name: mvn test
        run: mvn test
        working-directory: src

      - name: Build the stack
        working-directory: src
        run: |
          docker compose build
          docker compose up -d

      - name: Test
        working-directory: src
        run: |
          docker compose exec -T build curl -s --retry 10 --retry-connrefused http://127.0.0.1:80/gemp-swccg/index.html
          echo "Python3: $(which python3)"
          echo "pip3...: $(which pip3)"
          pip3 install -r requirements.txt
          python3 gemp_client_test.py
